### ISSUE TITLE
Can't start Shopware 5.0.1

### ISSUE THREAD

**Issue by zubairov** [kurthuwig/docker-shopware#1]
First of all, very nice approach! Making Shopware installation so much less painful! Very well done!

However can't make it run:

https://www.dropbox.com/s/zfhhgiha95mf9jh/Screenshot%202016-03-18%2011.56.20.png?dl=0

We are using a Docker Cloud following Stack image (Very similar to Docker-compose actually)

```
shopware:
  image: 'kurthuwig/shopware:5.0.1-1'
  environment:
    - DB_DATABASE=shopware
    - DB_HOST=foo
    - DB_PASSWORD=bar
    - DB_PORT=3306
    - DB_USER=shopware
    - PHPMYADMIN_PW=hasi
  ports:
    - '80:80'
  volumes:
    - '/tmp:/var/www/html'
```
